[package]
name = "ncmc_lib"
version = "0.4.0"
edition.workspace = true
license.workspace = true
description = "convert ncm to mp3 or flac ..."
documentation = "https://docs.rs/ncmc_lib"
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
thiserror = { workspace = true }
id3 = { version = "1.17" }
aes = "0.9"
ecb = { version = "0.2", features = ["alloc"] }
base64 = { version = "0.22" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
ureq = { version = "3.2", optional = true }
futures-core = { version = "0.3", optional = true }
futures-util = { version = "0.3", optional = true, features = ["io"] }
futures-sink = { version = "0.3", optional = true }
bytes = { version = "1", optional = true }

[features]
default = []
cover_download = ["dep:ureq"]
stream = ["dep:futures-core", "dep:futures-util", "dep:futures-sink", "dep:bytes"]

[dev-dependencies]
futures = "0.3"
